source 'https://cdn.cocoapods.org/'

use_frameworks!

platform :ios, '12.0'

# xcode 15.3 的坑 https://juejin.cn/post/7345687862530637834?utm_source=gold_browser_extension

target 'KcDebugSwift_Example' do
  pod 'KcDebugSwift', :path => '../'

  target 'KcDebugSwift_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
        end
    end
end
