source 'https://cdn.cocoapods.org/'
source 'https://code.badam.mobi/badambiz_ios/zpspecs.git'

use_frameworks!

platform :ios, '9.0'

target 'KcDebugSwift_Example' do
  pod 'KcDebugSwift', :path => '../'

  target 'KcDebugSwift_Tests' do
    inherit! :search_paths

    
  end
end
